# Generated by Django 6.1 on 2026-09-03 10:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_code', models.CharField(max_length=64, unique=True, verbose_name='OpenFoodFacts barcode')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('nova_group', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Unprocessed or minimally processed'), (2, 'Processed culinary ingredient'), (3, 'Processed food'), (4, 'Ultra-processed food')], null=True)),
                ('nutriscore_grade', models.CharField(blank=True, max_length=1)),
                ('energy_kcal', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('sugars_g', models.FloatField(blank=True, null=True)),
                ('salt_g', models.FloatField(blank=True, null=True)),
                ('plant_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('meal', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='lunch', max_length=16)),
                ('eaten_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='tracker.food')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-eaten_on', '-created_at'],
            },
        ),
    ]
